/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.main;

import java.awt.Color;

/**
 *
 * @author vduct
 */
public class UI_Staff extends javax.swing.JFrame {
    
    Color lightBlue = new Color(204,204,255);
    
    /**
     * Creates new form UI_Staff
     */
    public UI_Staff() {
        initComponents();
        
        pnlTra.setVisible(false);
        pnlThue.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLayoutSize = new javax.swing.JPanel();
        pnlNavigationBar = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblCD = new javax.swing.JLabel();
        sprtCD = new javax.swing.JSeparator();
        pnlMenu = new javax.swing.JPanel();
        tabThue = new javax.swing.JPanel();
        lblThue = new javax.swing.JLabel();
        tabTra = new javax.swing.JPanel();
        lblTra = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlThue = new javax.swing.JPanel();
        scrThue = new javax.swing.JScrollPane();
        tblThue = new javax.swing.JTable();
        pnlThue_TimKiem = new javax.swing.JPanel();
        lblThue_TimKiem_Ten = new javax.swing.JLabel();
        txtThue_TimKiem_Ten = new javax.swing.JTextField();
        btnThue_Tim = new javax.swing.JButton();
        pnlThue_Them = new javax.swing.JPanel();
        lblThue_CCCD = new javax.swing.JLabel();
        lblThue_MaDia = new javax.swing.JLabel();
        lblThue_SoLuong = new javax.swing.JLabel();
        lblThue_NgayTra = new javax.swing.JLabel();
        txtThue_CCCD = new javax.swing.JTextField();
        txtThue_MaDia = new javax.swing.JTextField();
        txtThue_SoLuong = new javax.swing.JTextField();
        txtThue_NgayTra = new javax.swing.JTextField();
        btnThue_OK = new javax.swing.JButton();
        pnlTra = new javax.swing.JPanel();
        scrTra = new javax.swing.JScrollPane();
        tblTra = new javax.swing.JTable();
        pnlTra_TimKiem = new javax.swing.JPanel();
        lblTra_TimKiem_CCCD = new javax.swing.JLabel();
        txtTra_TimKiem_CCCD = new javax.swing.JTextField();
        btnTra_Tim = new javax.swing.JButton();
        pnlTra_Them = new javax.swing.JPanel();
        lblTra_ID = new javax.swing.JLabel();
        lblTra_PhuPhi = new javax.swing.JLabel();
        txtTra_ID = new javax.swing.JTextField();
        txtTra_PhuPhi = new javax.swing.JTextField();
        btnTra_OK = new javax.swing.JButton();
        btnTra_Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STAFF");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlLayoutSize.setBackground(new java.awt.Color(102, 102, 255));

        pnlNavigationBar.setBackground(new java.awt.Color(102, 102, 255));
        pnlNavigationBar.setPreferredSize(new java.awt.Dimension(270, 500));
        pnlNavigationBar.setLayout(new java.awt.BorderLayout());

        pnlLogo.setBackground(new java.awt.Color(102, 102, 255));

        lblCD.setFont(new java.awt.Font("Script MT Bold", 3, 48)); // NOI18N
        lblCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCD.setText("CD");

        sprtCD.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCD, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprtCD, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sprtCD, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlNavigationBar.add(pnlLogo, java.awt.BorderLayout.PAGE_START);

        pnlMenu.setBackground(new java.awt.Color(102, 102, 255));
        pnlMenu.setMaximumSize(new java.awt.Dimension(282, 392));
        pnlMenu.setName(""); // NOI18N
        pnlMenu.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        tabThue.setBackground(new java.awt.Color(204, 204, 255));
        tabThue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabThueMouseClicked(evt);
            }
        });

        lblThue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblThue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThue.setText("Thuê sản phẩm");
        lblThue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout tabThueLayout = new javax.swing.GroupLayout(tabThue);
        tabThue.setLayout(tabThueLayout);
        tabThueLayout.setHorizontalGroup(
            tabThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabThueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThue, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabThueLayout.setVerticalGroup(
            tabThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabThueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThue, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabThue);

        tabTra.setBackground(new java.awt.Color(204, 204, 255));
        tabTra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTraMouseClicked(evt);
            }
        });

        lblTra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTra.setText("Trả sản phẩm");
        lblTra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout tabTraLayout = new javax.swing.GroupLayout(tabTra);
        tabTra.setLayout(tabTraLayout);
        tabTraLayout.setHorizontalGroup(
            tabTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTra, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabTraLayout.setVerticalGroup(
            tabTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTra, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabTra);

        pnlNavigationBar.add(pnlMenu, java.awt.BorderLayout.CENTER);

        pnlContent.setBackground(new java.awt.Color(204, 204, 255));
        pnlContent.setLayout(new java.awt.CardLayout());

        tblThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrThue.setViewportView(tblThue);

        pnlThue_TimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblThue_TimKiem_Ten.setText("Tên:");

        txtThue_TimKiem_Ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThue_TimKiem_TenActionPerformed(evt);
            }
        });

        btnThue_Tim.setText("Tìm");
        btnThue_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThue_TimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThue_TimKiemLayout = new javax.swing.GroupLayout(pnlThue_TimKiem);
        pnlThue_TimKiem.setLayout(pnlThue_TimKiemLayout);
        pnlThue_TimKiemLayout.setHorizontalGroup(
            pnlThue_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThue_TimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThue_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThue_TimKiemLayout.createSequentialGroup()
                        .addComponent(lblThue_TimKiem_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txtThue_TimKiem_Ten, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThue_TimKiemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThue_Tim)))
                .addContainerGap())
        );
        pnlThue_TimKiemLayout.setVerticalGroup(
            pnlThue_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThue_TimKiemLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlThue_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThue_TimKiem_Ten)
                    .addComponent(txtThue_TimKiem_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnThue_Tim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlThue_Them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblThue_CCCD.setText("CCCD:");

        lblThue_MaDia.setText("Mã đĩa:");

        lblThue_SoLuong.setText("Số lượng:");

        lblThue_NgayTra.setText("Ngày trả:");

        txtThue_MaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThue_MaDiaActionPerformed(evt);
            }
        });

        txtThue_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThue_SoLuongActionPerformed(evt);
            }
        });

        btnThue_OK.setText("OK");
        btnThue_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThue_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThue_ThemLayout = new javax.swing.GroupLayout(pnlThue_Them);
        pnlThue_Them.setLayout(pnlThue_ThemLayout);
        pnlThue_ThemLayout.setHorizontalGroup(
            pnlThue_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThue_ThemLayout.createSequentialGroup()
                .addGroup(pnlThue_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThue_ThemLayout.createSequentialGroup()
                        .addComponent(lblThue_NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThue_NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThue_ThemLayout.createSequentialGroup()
                        .addComponent(lblThue_SoLuong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThue_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThue_ThemLayout.createSequentialGroup()
                        .addComponent(lblThue_MaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtThue_MaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThue_ThemLayout.createSequentialGroup()
                        .addComponent(lblThue_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtThue_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThue_ThemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThue_OK)
                .addContainerGap())
        );
        pnlThue_ThemLayout.setVerticalGroup(
            pnlThue_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThue_ThemLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlThue_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThue_CCCD)
                    .addComponent(txtThue_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThue_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThue_MaDia)
                    .addComponent(txtThue_MaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlThue_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThue_SoLuong)
                    .addComponent(txtThue_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlThue_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThue_NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThue_NgayTra))
                .addGap(37, 37, 37)
                .addComponent(btnThue_OK)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlThueLayout = new javax.swing.GroupLayout(pnlThue);
        pnlThue.setLayout(pnlThueLayout);
        pnlThueLayout.setHorizontalGroup(
            pnlThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrThue, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThue_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThue_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlThueLayout.setVerticalGroup(
            pnlThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrThue)
                    .addGroup(pnlThueLayout.createSequentialGroup()
                        .addComponent(pnlThue_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlThue_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlContent.add(pnlThue, "card2");

        tblTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrTra.setViewportView(tblTra);

        pnlTra_TimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTra_TimKiem_CCCD.setText("CCCD:");

        btnTra_Tim.setText("Tìm");
        btnTra_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTra_TimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTra_TimKiemLayout = new javax.swing.GroupLayout(pnlTra_TimKiem);
        pnlTra_TimKiem.setLayout(pnlTra_TimKiemLayout);
        pnlTra_TimKiemLayout.setHorizontalGroup(
            pnlTra_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTra_TimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTra_TimKiem_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTra_TimKiem_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTra_TimKiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTra_Tim)
                .addContainerGap())
        );
        pnlTra_TimKiemLayout.setVerticalGroup(
            pnlTra_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTra_TimKiemLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(pnlTra_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTra_TimKiem_CCCD)
                    .addComponent(txtTra_TimKiem_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTra_Tim)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pnlTra_Them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTra_ID.setText("ID:");

        lblTra_PhuPhi.setText("Phụ phí:");

        btnTra_OK.setText("OK");
        btnTra_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTra_OKActionPerformed(evt);
            }
        });

        btnTra_Reset.setText("Reset");
        btnTra_Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTra_ResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTra_ThemLayout = new javax.swing.GroupLayout(pnlTra_Them);
        pnlTra_Them.setLayout(pnlTra_ThemLayout);
        pnlTra_ThemLayout.setHorizontalGroup(
            pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTra_ThemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTra_ThemLayout.createSequentialGroup()
                        .addComponent(btnTra_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTra_Reset))
                    .addGroup(pnlTra_ThemLayout.createSequentialGroup()
                        .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTra_ThemLayout.createSequentialGroup()
                                .addComponent(lblTra_PhuPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTra_PhuPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTra_ThemLayout.createSequentialGroup()
                                .addComponent(lblTra_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTra_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTra_ThemLayout.setVerticalGroup(
            pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTra_ThemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTra_ID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTra_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTra_PhuPhi)
                    .addComponent(txtTra_PhuPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTra_OK)
                    .addComponent(btnTra_Reset))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout pnlTraLayout = new javax.swing.GroupLayout(pnlTra);
        pnlTra.setLayout(pnlTraLayout);
        pnlTraLayout.setHorizontalGroup(
            pnlTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTra, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTra_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTra_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTraLayout.setVerticalGroup(
            pnlTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrTra, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addGroup(pnlTraLayout.createSequentialGroup()
                        .addComponent(pnlTra_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlTra_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlContent.add(pnlTra, "card3");

        javax.swing.GroupLayout pnlLayoutSizeLayout = new javax.swing.GroupLayout(pnlLayoutSize);
        pnlLayoutSize.setLayout(pnlLayoutSizeLayout);
        pnlLayoutSizeLayout.setHorizontalGroup(
            pnlLayoutSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayoutSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNavigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlLayoutSizeLayout.setVerticalGroup(
            pnlLayoutSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNavigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pnlNavigationBar.getAccessibleContext().setAccessibleName("Menu");

        getContentPane().add(pnlLayoutSize, java.awt.BorderLayout.CENTER);
        pnlLayoutSize.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabThueMouseClicked
        pnlThue.setVisible(true);
        
        pnlTra.setVisible(false);
        tabThue.setBackground(Color.white);
        
        tabTra.setBackground(lightBlue);
    }//GEN-LAST:event_tabThueMouseClicked

    private void tabTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTraMouseClicked
        pnlTra.setVisible(true);
       
        pnlThue.setVisible(false);
        tabTra.setBackground(Color.white);
        
        tabThue.setBackground(lightBlue);
    }//GEN-LAST:event_tabTraMouseClicked

    private void txtThue_TimKiem_TenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThue_TimKiem_TenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThue_TimKiem_TenActionPerformed

    private void btnThue_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThue_TimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThue_TimActionPerformed

    private void btnThue_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThue_OKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThue_OKActionPerformed

    private void txtThue_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThue_SoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThue_SoLuongActionPerformed

    private void btnTra_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTra_TimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTra_TimActionPerformed

    private void btnTra_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTra_OKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTra_OKActionPerformed

    private void btnTra_ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTra_ResetMouseClicked
        txtTra_ID.setText("");
        txtTra_PhuPhi.setText("");
    }//GEN-LAST:event_btnTra_ResetMouseClicked

    private void txtThue_MaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThue_MaDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThue_MaDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThue_OK;
    private javax.swing.JButton btnThue_Tim;
    private javax.swing.JButton btnTra_OK;
    private javax.swing.JButton btnTra_Reset;
    private javax.swing.JButton btnTra_Tim;
    private javax.swing.JLabel lblCD;
    private javax.swing.JLabel lblThue;
    private javax.swing.JLabel lblThue_CCCD;
    private javax.swing.JLabel lblThue_MaDia;
    private javax.swing.JLabel lblThue_NgayTra;
    private javax.swing.JLabel lblThue_SoLuong;
    private javax.swing.JLabel lblThue_TimKiem_Ten;
    private javax.swing.JLabel lblTra;
    private javax.swing.JLabel lblTra_ID;
    private javax.swing.JLabel lblTra_PhuPhi;
    private javax.swing.JLabel lblTra_TimKiem_CCCD;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlLayoutSize;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNavigationBar;
    private javax.swing.JPanel pnlThue;
    private javax.swing.JPanel pnlThue_Them;
    private javax.swing.JPanel pnlThue_TimKiem;
    private javax.swing.JPanel pnlTra;
    private javax.swing.JPanel pnlTra_Them;
    private javax.swing.JPanel pnlTra_TimKiem;
    private javax.swing.JScrollPane scrThue;
    private javax.swing.JScrollPane scrTra;
    private javax.swing.JSeparator sprtCD;
    private javax.swing.JPanel tabThue;
    private javax.swing.JPanel tabTra;
    private javax.swing.JTable tblThue;
    private javax.swing.JTable tblTra;
    private javax.swing.JTextField txtThue_CCCD;
    private javax.swing.JTextField txtThue_MaDia;
    private javax.swing.JTextField txtThue_NgayTra;
    private javax.swing.JTextField txtThue_SoLuong;
    private javax.swing.JTextField txtThue_TimKiem_Ten;
    private javax.swing.JTextField txtTra_ID;
    private javax.swing.JTextField txtTra_PhuPhi;
    private javax.swing.JTextField txtTra_TimKiem_CCCD;
    // End of variables declaration//GEN-END:variables
}
