/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.main;

import Helper.CustomUUID;
import Helper.DateConfig;
import Helper.RandomCodeGenerator;
import control.BlankValueException;
import control.InvalidIDException;
import control.LoginService;
import control.PayService;
import control.RentService;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.Disk;
import model.Payment;
import model.RentDetails;


/**
 *
 * @author vduct
 */
public class UI_Staff extends javax.swing.JFrame {
    
    Color lightBlue = new Color(204,204,255);
    
    private int countAffCol = 0;
    private String idThue;
    private RentService rentService = new RentService();
    private List<Disk> disks = new ArrayList<Disk>();
    private DefaultTableModel defTabMod = new DefaultTableModel();
    
    private LoginService login;
    private RandomCodeGenerator uID; 
    private RentDetails rentDt;
    private List<RentDetails> rentDtls = new ArrayList<>();
    private List<Payment> pms = null;
    private PayService payService = null;

    private DateConfig dcf = null;
    private List<Customer> customers = null;
    
    /**
     * Creates new form UI_Staff
     */
    public UI_Staff() {
        initComponents();
        setHomePage();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgThue = new javax.swing.JDialog();
        pnlThue_Them1 = new javax.swing.JPanel();
        lblThue_MAKH = new javax.swing.JLabel();
        lblThue_MaDia1 = new javax.swing.JLabel();
        lblThue_SoLuong1 = new javax.swing.JLabel();
        lblThue_NgayTra1 = new javax.swing.JLabel();
        txtThue_MaKH = new javax.swing.JTextField();
        txtThue_MaDia = new javax.swing.JTextField();
        txtThue_SoLuong = new javax.swing.JTextField();
        btnThue_Luu = new javax.swing.JButton();
        txtThue_NgayTra = new com.toedter.calendar.JDateChooser();
        dlgTra = new javax.swing.JDialog();
        pnlTra_Them = new javax.swing.JPanel();
        btnOkTra = new javax.swing.JButton();
        txtTra_ID = new javax.swing.JTextField();
        txtTra_PhuPhi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThue_Huy = new javax.swing.JButton();
        dlgDmk = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txtMkcu = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtMkmoi = new javax.swing.JPasswordField();
        btnHome_pass_OK = new javax.swing.JButton();
        frmPerInf = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHome_mnv = new javax.swing.JLabel();
        txtHome_CCCD = new javax.swing.JLabel();
        txtHome_ht = new javax.swing.JLabel();
        txtHome_gt = new javax.swing.JLabel();
        txtHome_ns = new javax.swing.JLabel();
        btnHome_Inf_OK = new javax.swing.JButton();
        pnlLayoutSize = new javax.swing.JPanel();
        pnlNavigationBar = new javax.swing.JPanel();
        lblCD = new javax.swing.JLabel();
        sprtCD = new javax.swing.JSeparator();
        tabHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        tabThue = new javax.swing.JPanel();
        lblThue = new javax.swing.JLabel();
        tabTra = new javax.swing.JPanel();
        lblTra = new javax.swing.JLabel();
        tabTheKH = new javax.swing.JPanel();
        lblTheKH = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnLogout = new javax.swing.JButton();
        btnDMK = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnTTND = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblCD1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlThue = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThue = new javax.swing.JTable();
        pnlThueProcess = new javax.swing.JPanel();
        txtTimKiemThue = new javax.swing.JTextField();
        btnTimKiemThue = new javax.swing.JButton();
        btnThue = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnRstThue = new javax.swing.JButton();
        txtThongBaoThue = new javax.swing.JLabel();
        pnlTra = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtTKTra = new javax.swing.JTextField();
        btnTK = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnTra = new javax.swing.JButton();
        btnResetTra = new javax.swing.JButton();
        txtThongBaoTra = new javax.swing.JLabel();
        btnXuatHoaDon = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTra = new javax.swing.JTable();
        pnlTheKH = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTheKH = new javax.swing.JTable();
        pnlTheKHProcess = new javax.swing.JPanel();
        txtTimKiemTheKH = new javax.swing.JTextField();
        btnTimKiemTheKH = new javax.swing.JButton();
        btnThemKH = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnRstTheKH = new javax.swing.JButton();
        txtThongBaoTheKH = new javax.swing.JLabel();

        dlgThue.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgThue.setTitle("Phiếu thuê");
        dlgThue.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlgThue.setResizable(false);
        dlgThue.setSize(new java.awt.Dimension(377, 300));

        pnlThue_Them1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlThue_Them1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThue_MAKH.setText("Mã khách hàng:");
        pnlThue_Them1.add(lblThue_MAKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, -1));

        lblThue_MaDia1.setText("Mã đĩa:");
        pnlThue_Them1.add(lblThue_MaDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, -1));

        lblThue_SoLuong1.setText("Số lượng:");
        pnlThue_Them1.add(lblThue_SoLuong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, -1));

        lblThue_NgayTra1.setText("Ngày trả:");
        pnlThue_Them1.add(lblThue_NgayTra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, -1));
        pnlThue_Them1.add(txtThue_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 47, 149, -1));
        pnlThue_Them1.add(txtThue_MaDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 87, 149, -1));
        pnlThue_Them1.add(txtThue_SoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 148, -1));

        btnThue_Luu.setText("Save");
        btnThue_Luu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThue_LuuMouseClicked(evt);
            }
        });
        pnlThue_Them1.add(btnThue_Luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        txtThue_NgayTra.setDateFormatString("dd-MM-yyyy ");
        pnlThue_Them1.add(txtThue_NgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 150, -1));

        dlgThue.getContentPane().add(pnlThue_Them1, java.awt.BorderLayout.CENTER);

        dlgTra.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgTra.setBackground(new java.awt.Color(255, 255, 255));
        dlgTra.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlgTra.setResizable(false);
        dlgTra.setSize(new java.awt.Dimension(400, 217));

        pnlTra_Them.setBackground(new java.awt.Color(255, 255, 255));

        btnOkTra.setText("OK");
        btnOkTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkTraMouseClicked(evt);
            }
        });

        jLabel1.setText("Mã phiếu thuê:");

        jLabel2.setText("Phụ phí:");

        javax.swing.GroupLayout pnlTra_ThemLayout = new javax.swing.GroupLayout(pnlTra_Them);
        pnlTra_Them.setLayout(pnlTra_ThemLayout);
        pnlTra_ThemLayout.setHorizontalGroup(
            pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTra_ThemLayout.createSequentialGroup()
                .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTra_ThemLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTra_PhuPhi, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtTra_ID)))
                    .addGroup(pnlTra_ThemLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOkTra)))
                .addGap(78, 78, 78))
        );
        pnlTra_ThemLayout.setVerticalGroup(
            pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTra_ThemLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTra_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlTra_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTra_PhuPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOkTra)
                .addGap(32, 32, 32))
        );

        dlgTra.getContentPane().add(pnlTra_Them, java.awt.BorderLayout.LINE_START);

        btnThue_Huy.setText("Cancel");
        btnThue_Huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThue_HuyMouseClicked(evt);
            }
        });

        dlgDmk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dlgDmk.setSize(new java.awt.Dimension(396, 168));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mật khẩu cũ:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mật khẩu mới:");

        btnHome_pass_OK.setText("Ok");

        javax.swing.GroupLayout dlgDmkLayout = new javax.swing.GroupLayout(dlgDmk.getContentPane());
        dlgDmk.getContentPane().setLayout(dlgDmkLayout);
        dlgDmkLayout.setHorizontalGroup(
            dlgDmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDmkLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(dlgDmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDmkLayout.createSequentialGroup()
                        .addGroup(dlgDmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgDmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMkcu, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDmkLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHome_pass_OK)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        dlgDmkLayout.setVerticalGroup(
            dlgDmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDmkLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(dlgDmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMkcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgDmkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnHome_pass_OK)
                .addGap(34, 34, 34))
        );

        frmPerInf.setTitle("Thông tin Nhân viên");
        frmPerInf.setBackground(new java.awt.Color(255, 255, 255));
        frmPerInf.setSize(new java.awt.Dimension(580, 334));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_info.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Mã nhân vên:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Họ tên:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Giới tính:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("CCCD:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Ngày sinh:");

        btnHome_Inf_OK.setText("OK");

        javax.swing.GroupLayout frmPerInfLayout = new javax.swing.GroupLayout(frmPerInf.getContentPane());
        frmPerInf.getContentPane().setLayout(frmPerInfLayout);
        frmPerInfLayout.setHorizontalGroup(
            frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPerInfLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHome_Inf_OK)
                    .addGroup(frmPerInfLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(103, 103, 103)
                        .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHome_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_ht, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_mnv, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_ns, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        frmPerInfLayout.setVerticalGroup(
            frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPerInfLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPerInfLayout.createSequentialGroup()
                        .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_mnv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_ht, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frmPerInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_ns, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnHome_Inf_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STAFF");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1064, 678));

        pnlLayoutSize.setBackground(new java.awt.Color(102, 102, 255));

        pnlNavigationBar.setBackground(new java.awt.Color(102, 102, 255));
        pnlNavigationBar.setPreferredSize(new java.awt.Dimension(270, 500));

        lblCD.setFont(new java.awt.Font("Script MT Bold", 3, 48)); // NOI18N
        lblCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCD.setText("CD");

        sprtCD.setForeground(new java.awt.Color(0, 0, 0));

        tabHome.setBackground(new java.awt.Color(204, 204, 255));
        tabHome.setPreferredSize(new java.awt.Dimension(270, 81));
        tabHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabHomeMouseClicked(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setText("Trang chủ");

        javax.swing.GroupLayout tabHomeLayout = new javax.swing.GroupLayout(tabHome);
        tabHome.setLayout(tabHomeLayout);
        tabHomeLayout.setHorizontalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        tabHomeLayout.setVerticalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabHomeLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabThue.setBackground(new java.awt.Color(204, 204, 255));
        tabThue.setPreferredSize(new java.awt.Dimension(270, 81));
        tabThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabThueMouseClicked(evt);
            }
        });

        lblThue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblThue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThue.setText("Thuê sản phẩm");
        lblThue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout tabThueLayout = new javax.swing.GroupLayout(tabThue);
        tabThue.setLayout(tabThueLayout);
        tabThueLayout.setHorizontalGroup(
            tabThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabThueLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblThue, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        tabThueLayout.setVerticalGroup(
            tabThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabThueLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblThue, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        tabTra.setBackground(new java.awt.Color(204, 204, 255));
        tabTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTraMouseClicked(evt);
            }
        });

        lblTra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTra.setText("Trả sản phẩm");
        lblTra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout tabTraLayout = new javax.swing.GroupLayout(tabTra);
        tabTra.setLayout(tabTraLayout);
        tabTraLayout.setHorizontalGroup(
            tabTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTraLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblTra, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        tabTraLayout.setVerticalGroup(
            tabTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTra, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabTheKH.setBackground(new java.awt.Color(204, 204, 255));
        tabTheKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTheKHMouseClicked(evt);
            }
        });

        lblTheKH.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTheKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTheKH.setText("Thẻ khách hàng");
        lblTheKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout tabTheKHLayout = new javax.swing.GroupLayout(tabTheKH);
        tabTheKH.setLayout(tabTheKHLayout);
        tabTheKHLayout.setHorizontalGroup(
            tabTheKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTheKHLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblTheKH, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        tabTheKHLayout.setVerticalGroup(
            tabTheKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTheKHLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblTheKH)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout pnlNavigationBarLayout = new javax.swing.GroupLayout(pnlNavigationBar);
        pnlNavigationBar.setLayout(pnlNavigationBarLayout);
        pnlNavigationBarLayout.setHorizontalGroup(
            pnlNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationBarLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(pnlNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCD, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprtCD, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlNavigationBarLayout.createSequentialGroup()
                .addGroup(pnlNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabTheKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabThue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabHome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlNavigationBarLayout.setVerticalGroup(
            pnlNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblCD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprtCD, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabHome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabThue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabTheKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContent.setBackground(new java.awt.Color(204, 204, 255));
        pnlContent.setOpaque(false);
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(102, 200, 255));
        pnlHome.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator3);

        btnLogout.setBackground(new java.awt.Color(242, 242, 242));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log_out.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMargin(new java.awt.Insets(2, 16, 3, 16));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btnDMK.setBackground(new java.awt.Color(242, 242, 242));
        btnDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change_pass.png"))); // NOI18N
        btnDMK.setText("Đổi mật khẩu");
        btnDMK.setFocusable(false);
        btnDMK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDMK.setMargin(new java.awt.Insets(2, 16, 3, 16));
        btnDMK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDMKMouseClicked(evt);
            }
        });
        jToolBar1.add(btnDMK);
        jToolBar1.add(jSeparator5);

        btnTTND.setBackground(new java.awt.Color(242, 242, 242));
        btnTTND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/per_info.png"))); // NOI18N
        btnTTND.setText("Thông tin người dùng");
        btnTTND.setFocusable(false);
        btnTTND.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTTND.setMargin(new java.awt.Insets(2, 16, 3, 16));
        btnTTND.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTTND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTTNDMouseClicked(evt);
            }
        });
        jToolBar1.add(btnTTND);

        pnlHome.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signal.png"))); // NOI18N

        jLabel7.setText("Hệ thống quản lý ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(633, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        pnlHome.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(102, 200, 255));

        lblCD1.setFont(new java.awt.Font("Script MT Bold", 3, 48)); // NOI18N
        lblCD1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCD1.setText("CD");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo - Copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(lblCD1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCD1)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        pnlHome.add(jPanel7, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlHome, "card4");

        pnlThue.setBackground(new java.awt.Color(255, 255, 255));

        tblThue.setAutoCreateRowSorter(true);
        tblThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblThue);

        pnlThueProcess.setBackground(new java.awt.Color(255, 255, 255));

        btnTimKiemThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (2).png"))); // NOI18N
        btnTimKiemThue.setText("Tìm Kiếm");
        btnTimKiemThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemThueMouseClicked(evt);
            }
        });

        btnThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Thực thi.png"))); // NOI18N
        btnThue.setText("Thuê");
        btnThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThueMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnRstThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        btnRstThue.setText("Reset");
        btnRstThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRstThueActionPerformed(evt);
            }
        });

        txtThongBaoThue.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pnlThueProcessLayout = new javax.swing.GroupLayout(pnlThueProcess);
        pnlThueProcess.setLayout(pnlThueProcessLayout);
        pnlThueProcessLayout.setHorizontalGroup(
            pnlThueProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThueProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemThue, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiemThue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThueProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThueProcessLayout.createSequentialGroup()
                        .addComponent(txtThongBaoThue, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlThueProcessLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRstThue)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlThueProcessLayout.setVerticalGroup(
            pnlThueProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThueProcessLayout.createSequentialGroup()
                .addGroup(pnlThueProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThueProcessLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlThueProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThueProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThue)
                                .addComponent(btnRstThue))
                            .addGroup(pnlThueProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTimKiemThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTimKiemThue))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThongBaoThue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlThueLayout = new javax.swing.GroupLayout(pnlThue);
        pnlThue.setLayout(pnlThueLayout);
        pnlThueLayout.setHorizontalGroup(
            pnlThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThueProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        pnlThueLayout.setVerticalGroup(
            pnlThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThueLayout.createSequentialGroup()
                .addComponent(pnlThueProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
        );

        pnlContent.add(pnlThue, "card2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (2).png"))); // NOI18N
        btnTK.setText("Tìm kiếm");
        btnTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Thực thi.png"))); // NOI18N
        btnTra.setText("Trả");
        btnTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTraMouseClicked(evt);
            }
        });

        btnResetTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        btnResetTra.setText("Reset");
        btnResetTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetTraMouseClicked(evt);
            }
        });

        txtThongBaoTra.setForeground(new java.awt.Color(255, 51, 51));

        btnXuatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        btnXuatHoaDon.setText("Xuất hóa đơn");
        btnXuatHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatHoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThongBaoTra, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTKTra, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetTra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXuatHoaDon)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetTra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtTKTra)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThongBaoTra)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tblTra.setAutoCreateRowSorter(true);
        tblTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTra);

        javax.swing.GroupLayout pnlTraLayout = new javax.swing.GroupLayout(pnlTra);
        pnlTra.setLayout(pnlTraLayout);
        pnlTraLayout.setHorizontalGroup(
            pnlTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        pnlTraLayout.setVerticalGroup(
            pnlTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTraLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlContent.add(pnlTra, "card3");

        pnlTheKH.setBackground(new java.awt.Color(255, 255, 255));

        tblTheKH.setAutoCreateRowSorter(true);
        tblTheKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblTheKH);

        pnlTheKHProcess.setBackground(new java.awt.Color(255, 255, 255));

        btnTimKiemTheKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (2).png"))); // NOI18N
        btnTimKiemTheKH.setText("Tìm Kiếm");
        btnTimKiemTheKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemTheKHMouseClicked(evt);
            }
        });

        btnThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Thực thi.png"))); // NOI18N
        btnThemKH.setText("Thêm");
        btnThemKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemKHMouseClicked(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnRstTheKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        btnRstTheKH.setText("Reset");
        btnRstTheKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRstTheKHActionPerformed(evt);
            }
        });

        txtThongBaoTheKH.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pnlTheKHProcessLayout = new javax.swing.GroupLayout(pnlTheKHProcess);
        pnlTheKHProcess.setLayout(pnlTheKHProcessLayout);
        pnlTheKHProcessLayout.setHorizontalGroup(
            pnlTheKHProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheKHProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemTheKH, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiemTheKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTheKHProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTheKHProcessLayout.createSequentialGroup()
                        .addComponent(txtThongBaoTheKH, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlTheKHProcessLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRstTheKH)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlTheKHProcessLayout.setVerticalGroup(
            pnlTheKHProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheKHProcessLayout.createSequentialGroup()
                .addGroup(pnlTheKHProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTheKHProcessLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlTheKHProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTheKHProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThemKH)
                                .addComponent(btnRstTheKH))
                            .addGroup(pnlTheKHProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTimKiemTheKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTimKiemTheKH))))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThongBaoTheKH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTheKHLayout = new javax.swing.GroupLayout(pnlTheKH);
        pnlTheKH.setLayout(pnlTheKHLayout);
        pnlTheKHLayout.setHorizontalGroup(
            pnlTheKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTheKHProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        pnlTheKHLayout.setVerticalGroup(
            pnlTheKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTheKHLayout.createSequentialGroup()
                .addComponent(pnlTheKHProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE))
        );

        pnlContent.add(pnlTheKH, "card2");

        javax.swing.GroupLayout pnlLayoutSizeLayout = new javax.swing.GroupLayout(pnlLayoutSize);
        pnlLayoutSize.setLayout(pnlLayoutSizeLayout);
        pnlLayoutSizeLayout.setHorizontalGroup(
            pnlLayoutSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayoutSizeLayout.createSequentialGroup()
                .addComponent(pnlNavigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLayoutSizeLayout.setVerticalGroup(
            pnlLayoutSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigationBar, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNavigationBar.getAccessibleContext().setAccessibleName("Menu");

        getContentPane().add(pnlLayoutSize, java.awt.BorderLayout.CENTER);
        pnlLayoutSize.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThueMouseClicked
        this.dlgThue.setLocationRelativeTo(this);
        this.dlgThue.setVisible(true);
        
    }//GEN-LAST:event_btnThueMouseClicked

    private void btnThue_HuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThue_HuyMouseClicked
        this.dcf = new DateConfig();
        this.txtThongBaoThue.setText(""+this.dcf.getDate(txtThue_NgayTra));
    }//GEN-LAST:event_btnThue_HuyMouseClicked

    private void btnTimKiemThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemThueMouseClicked
        this.txtThongBaoThue.setText("");
        this.showTKDiskInfo(txtTimKiemThue.getText());
    }//GEN-LAST:event_btnTimKiemThueMouseClicked

    private void btnRstThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRstThueActionPerformed
        resetTableThue();        
    }//GEN-LAST:event_btnRstThueActionPerformed

    private void btnThue_LuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThue_LuuMouseClicked
        getRentForm();
        txtThongBaoThue.setText("Số dòng bị ảnh hưởng trên Csdl là "+ this.countAffCol + " !");
    }//GEN-LAST:event_btnThue_LuuMouseClicked

    private void btnTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMouseClicked
        this.txtThongBaoTra.setText("");
        this.showTKRentInfo(this.txtTKTra.getText());
    }//GEN-LAST:event_btnTKMouseClicked

    private void btnResetTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetTraMouseClicked
        resetTableTra();
    }//GEN-LAST:event_btnResetTraMouseClicked

    private void btnTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTraMouseClicked
        this.dlgTra.setLocationRelativeTo(this);
        this.dlgTra.setVisible(true);
    }//GEN-LAST:event_btnTraMouseClicked

    private void btnOkTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkTraMouseClicked
        getPhieuTra(); 
        txtThongBaoTra.setText("Phiếu trả đã được lưu!");
    }//GEN-LAST:event_btnOkTraMouseClicked

    private void btnXuatHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatHoaDonMouseClicked
        xuatHoaDon();
        txtThongBaoTra.setText("Số dòng bị ảnh hưởng trên Csdl là "+ this.countAffCol + " !");
    }//GEN-LAST:event_btnXuatHoaDonMouseClicked

    private void btnTimKiemTheKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemTheKHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemTheKHMouseClicked

    private void btnThemKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemKHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemKHMouseClicked

    private void btnRstTheKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRstTheKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRstTheKHActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        new UI_Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void tabTheKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTheKHMouseClicked
        pnlThue.setVisible(false);
        pnlTra.setVisible(false);
        pnlTheKH.setVisible(true);
        pnlHome.setVisible(false);
        tabTheKH.setBackground(Color.white);
        tabTra.setBackground(lightBlue);
        tabHome.setBackground(lightBlue);
        tabThue.setBackground(lightBlue);
        this.defTabMod.setColumnCount(0);
        this.defTabMod.setRowCount(0);
        showThongTinTheKH();
    }//GEN-LAST:event_tabTheKHMouseClicked

    private void tabTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTraMouseClicked
        pnlThue.setVisible(false);
        pnlTra.setVisible(true);
        pnlTheKH.setVisible(false);
        pnlHome.setVisible(false);
        tabTra.setBackground(Color.white);
        tabHome.setBackground(lightBlue);
        tabTheKH.setBackground(lightBlue);
        tabThue.setBackground(lightBlue);
        this.defTabMod.setColumnCount(0);
        this.defTabMod.setRowCount(0);
        showThongTinTra();
    }//GEN-LAST:event_tabTraMouseClicked

    private void tabThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabThueMouseClicked
        pnlThue.setVisible(true);
        pnlTra.setVisible(false);
        pnlTheKH.setVisible(false);
        pnlHome.setVisible(false);
        tabThue.setBackground(Color.white);
        tabTra.setBackground(lightBlue);
        tabTheKH.setBackground(lightBlue);
        tabHome.setBackground(lightBlue);
        this.defTabMod.setColumnCount(0);
        this.defTabMod.setRowCount(0);
        showThongTinThue();
    }//GEN-LAST:event_tabThueMouseClicked

    private void tabHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHomeMouseClicked
        setHomePage();
    }//GEN-LAST:event_tabHomeMouseClicked

    private void btnDMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMKMouseClicked
        this.dlgDmk.setVisible(true);
        this.dlgDmk.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnDMKMouseClicked

    private void btnTTNDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTNDMouseClicked
        this.frmPerInf.setVisible(true);
        this.frmPerInf.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnTTNDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Staff().setVisible(true);
            }
        });
    }
    /**HIỆN BẢNG DANH SÁCH ĐĨA SẴN SÀNG
     * @params NONE
    */
    public void showThongTinThue(){
        
        this.tblThue.setModel(defTabMod);
        
        this.disks = this.rentService.getAllDisk();
        
        defTabMod.addColumn("Mã đĩa");
        defTabMod.addColumn("Tên đĩa");
        defTabMod.addColumn("Loại");
        defTabMod.addColumn("Số lượng");
        defTabMod.addColumn("Giá thuê");
        
        for(Disk disk : disks){
            defTabMod.addRow(new Object[] {
                disk.getMa(), disk.getTen(), disk.getLoai(), disk.getSoluong(), disk.getGia()
            });
        }
        
    }
    
    /**HIỆN THÔNG TIN ĐĨA TÌM KIẾM
     * @param tenDia
     * @params String 
    */
    public void showTKDiskInfo(String tenDia){
        this.defTabMod.setRowCount(0);
        boolean flag = false;
        
        //Kiểm tra tên đĩa có tồn tại không
        for(Disk disk : this.disks){

            //Nếu có thì hiện hàng thông tin đĩa đó ra
            if(disk.getTen().trim().equals(tenDia)){                
                defTabMod.addRow(new Object[] {
                disk.getMa(), disk.getTen(), disk.getLoai(), disk.getSoluong(), disk.getGia()
                });
                flag = true;
            }
        }
        //không tìm được thì thông báo cho người dùng 
        if(flag == false) this.txtThongBaoThue.setText("Không có đĩa nào hợp lệ!");
    }
    
    /**NHẬP PHIẾU THUÊ
     * @params NONE
    */
    public void getRentForm(){
        boolean flag = true;
        rentDt = new RentDetails();
        customers = new ArrayList<>(); //Để check có viết sai mã khách hàng không
        this.customers = this.rentService.getAllCust();
        this.uID = new RandomCodeGenerator();
        this.dcf = new DateConfig();
        
        try{
            //Kiểm tra các trường có bị trống không
            if(txtThue_MaKH.getText().equals("") || txtThue_MaDia.getText().equals("") || txtThue_SoLuong.getText().equals("") || 
                    this.dcf.getDate(txtThue_NgayTra).equals("")){
                throw new BlankValueException("Thiếu thông tin!");
            }
            
            //Kiểm tra mã id thuê sinh ra có trùng không và tạo mới mã nếu trùng 
            this.rentDtls = this.rentService.getAllRent();
            do{
                this.idThue = RandomCodeGenerator.generateCode();
                

                for(RentDetails rent : rentDtls){
                    flag = !rent.getId().equals(idThue);
                }
               
            }while(flag == false);
            
            this.rentDtls.clear();
            

            
            //lấy dữ liệu vào rent details
            if(this.rentService.check_InvalidDisk(this.txtThue_MaDia.getText())){
                rentDt.setMadia(txtThue_MaDia.getText()); 
            }else{
                throw new InvalidIDException("Không tồn tại đĩa!");
            }
                       
            rentDt.setSlThue(Integer.parseInt(this.txtThue_SoLuong.getText()));
            rentDt.setNgayTra(this.dcf.getDate(txtThue_NgayTra));
            
            
            //kiểm tra xem mã khách hàng nhập vào có tồn tại không
            if(!this.rentService.chkIDCustomer(this.txtThue_MaKH.getText(), customers)){
                flag = false;    
                throw new InvalidIDException("Không tìm thấy khách hàng!");    
            }
            //Nếu có thì thêm mã khách hàng
            rentDt.setMaKh(this.txtThue_MaKH.getText());        
            this.customers.clear();            
        }catch(BlankValueException e){
            JOptionPane.showMessageDialog(this, e.toString());
        }catch(InvalidIDException e){
            JOptionPane.showMessageDialog(this, e.toString());
        }
        
        //Dòng này để xử lý khi người dùng nhập sai hay thiếu giá trị sẽ giữ nguyên dialog thuê nếu đúng hết sẽ hỏi lại người dùng có chắc chắn không và đòng dialog, cập nhật bảng đĩa.
        if(txtThue_MaKH.getText().equals("") || txtThue_MaDia.getText().equals("") || txtThue_SoLuong.getText().equals("") || 
                    this.dcf.getDate(txtThue_NgayTra).equals("") || flag == false){
            this.txtThongBaoThue.setText("");
        }else{
            int x = JOptionPane.showConfirmDialog(this, "Are you sure you want to save this change?");
            if(x == JOptionPane.YES_OPTION){
                this.countAffCol = this.rentService.insertRent(rentDt, LoginService.getId(), idThue);
            }
            this.dlgThue.dispose();
            setTableThue();
        }
      
    }
    
    /**reset table thuê
     * @param 
     * @return 
     */
    public void resetTableThue(){
        this.defTabMod.setRowCount(0);
//        this.txtThongBao.setText("");
        for(Disk disk : disks){
            defTabMod.addRow(new Object[] {
                disk.getMa(), disk.getTen(), disk.getLoai(), disk.getSoluong(), disk.getGia()
            });
        }
    }
    
    public void setTableThue(){
        this.defTabMod.setRowCount(0);
        this.disks = this.rentService.getAllDisk();
        for(Disk disk : disks){
            defTabMod.addRow(new Object[] {
                disk.getMa(), disk.getTen(), disk.getLoai(), disk.getSoluong(), disk.getGia()
            });
        }
    }
    
    
    /**Hiện bảng danh sách phiếu thuê
     * @param 
     */
    public void showThongTinTra(){
        
        this.tblTra.setModel(defTabMod);
        
        this.rentDtls = this.rentService.getAllRentNotPay();
        
        defTabMod.addColumn("Mã phiếu thuê");
        defTabMod.addColumn("Mã đĩa");
        defTabMod.addColumn("Mã khách hàng");
        defTabMod.addColumn("Số lượng thuê");
        defTabMod.addColumn("Giá thuê");
        defTabMod.addColumn("Ngày thuê");
        defTabMod.addColumn("Ngày trả");
        
        for(RentDetails rent : this.rentDtls){
            defTabMod.addRow(new Object[] {
                rent.getId(), rent.getMadia(), rent.getMaKh(), rent.getSlThue(), rent.getGia(), rent.getNgayThue(), rent.getNgayTra()
            });
        }
        this.rentDtls.clear();
    }
    
    /**HIỆN THÔNG TIN PHIẾU THUÊ CẦN TÌM
     * @param makh
     * @params String 
    */
    public void showTKRentInfo(String makh){
        this.defTabMod.setRowCount(0);
        boolean flag = false;
        this.rentDtls = this.rentService.getAllRentNotPay();
        
        //Kiểm tra tên đĩa có tồn tại không
        for(RentDetails rent : this.rentDtls){
            //Nếu có thì hiện hàng thông tin đĩa đó ra
            if(rent.getMaKh().trim().equals(makh)){                
                defTabMod.addRow(new Object[] {
                rent.getId(), rent.getMadia(), rent.getMaKh(), rent.getSlThue(), rent.getGia(), rent.getNgayThue(), rent.getNgayTra()
                });
                flag = true;
            }
        }
        //không tìm được thì thông báo cho người dùng 
        if(flag == false) this.txtThongBaoTra.setText("Không có đĩa nào hợp lệ!");
        
        this.rentDtls.clear();
    }
    
    /**reset table trả
     * @param 
     * @return 
     */
    public void resetTableTra(){
        //Giải phóng danh sách phiếu trả
        this.pms = null;
        
        this.defTabMod.setRowCount(0);
        this.rentDtls = this.rentService.getAllRentNotPay();
        
        for(RentDetails rent : this.rentDtls){
            defTabMod.addRow(new Object[] {
                rent.getId(), rent.getMadia(), rent.getMaKh(), rent.getSlThue(), rent.getGia(), rent.getNgayThue(), rent.getNgayTra()
            });
        }
        
        this.rentDtls.clear();
    }
    
    /**XỬ LÝ PHIẾU TRẢ KHI ẤN OK Ở DIALOG TRẢ
     * @param
     */
    public void getPhieuTra(){
        boolean flag = true;
        payService = new PayService();
        rentDtls = this.rentService.getAllRentNotPay();
        Payment pm = new Payment();
        pms = new ArrayList<>();
        List<Payment> pays = new ArrayList<>();
        pays = this.payService.getAllPay();
        
        try{
            //Kiểm tra trường có bị trống không
            if(this.txtTra_ID.getText().equals("") || this.txtTra_PhuPhi.getText().equals("")){
                throw new BlankValueException("Thiếu thông tin!");
            }
            
            
            //lấy dữ liệu vào payment(phiếu trả)        
            
            pm.setPhuPhi(Integer.parseInt(this.txtTra_PhuPhi.getText())); 

            
                //kiểm tra xem mã phiếu thuê nhập vào có tồn tại không
                if(this.payService.checkIdRent(this.txtTra_ID.getText(), rentDtls)){
                    flag = false;
                    throw new InvalidIDException("Không tìm thấy phiếu thuê!");
                }
                this.idThue = this.txtTra_ID.getText(); 
                
            
            //Tạo mã phiếu trả tự động
            pays = this.payService.getAllPay();
            do{
                pm.setMaPtra(RandomCodeGenerator.generateCode()); 
                
                for(Payment pay : pays){
                    flag = !pay.getMaPtra().trim().equals(pm.getMaPtra());
                }
 
            }while(flag == false);      
           
            //Thêm phiếu trả vào danh sách phiếu trả
            pms.add(pm);
            
            //Giải phóng đối tượng pm
            pm = null;
            
            this.rentDtls.clear();
        }catch(BlankValueException e){
            JOptionPane.showMessageDialog(this, e.toString());
        }catch(InvalidIDException e){
            JOptionPane.showMessageDialog(this, e.toString());
        }
        
        //Dòng này để xử lý khi người dùng nhập sai hay thiếu giá trị sẽ giữ nguyên dialog trả nếu đúng hết sẽ hỏi lại người dùng có chắc chắn không và đòng dialog, cập nhật bảng thuê.
        if(this.txtTra_ID.getText().equals("") || this.txtTra_PhuPhi.getText().equals("") || flag == false){
            this.txtThongBaoTra.setText("");
        }else{
            int x = JOptionPane.showConfirmDialog(this, "Are you sure you want to save this change?");
            if(x == JOptionPane.YES_OPTION){
             
            }
            this.dlgTra.dispose();
            setTableTra();
        }
    }
    
    public void setTableTra(){
        this.defTabMod.setRowCount(0);
        this.rentDtls = this.rentService.getAllRentNotPay();
                
        for(RentDetails rent : this.rentDtls){
            defTabMod.addRow(new Object[] {
                rent.getId(), rent.getMadia(), rent.getMaKh(), rent.getSlThue(), rent.getGia(), rent.getNgayThue(), rent.getNgayTra()
            });
        }
        this.rentDtls.clear();
    }
    
    public void xuatHoaDon(){
        boolean flag = true;
        String mahd;
        List<Payment> pays = new ArrayList<>();
        pays = this.payService.getAllPay();
        
        //Tạo mã hóa đơn tự động
        do{
                mahd = RandomCodeGenerator.generateCode();

                for(Payment pay : pays){
                    flag = !pay.getMaHd().trim().equals(mahd.trim());
                }
  
            }while(flag == false);
        
        //Chạy for để nhập phiếu trả cùng hóa đơn vào CSDL
        for(Payment pay : this.pms){
            pay.setMaHd(mahd);
           this.countAffCol = this.payService.insertPay(pay, idThue, LoginService.getId()); 
        }
        
    }
    
    public void setBtnThue(){
        this.txtThue_MaDia.setText("");
        this.txtThue_MaKH.setText("");        
        this.txtThue_SoLuong.setText("");
    }
    
    /**HIỆN BẢNG DANH SÁCH THẺ KHÁCH HÀNG
     * @params NONE
    */
    public void showThongTinTheKH(){
        
        this.tblTheKH.setModel(defTabMod);
                
        this.customers = this.rentService.getAllCust();
        
        defTabMod.addColumn("Mã khách hàng");
        defTabMod.addColumn("Căn cước công dân");
        defTabMod.addColumn("Họ tên");
        defTabMod.addColumn("Giới tính");
        defTabMod.addColumn("Ngày sinh");
        defTabMod.addColumn("Số điện thoại");
        defTabMod.addColumn("Email");
        defTabMod.addColumn("Địa chỉ");
        
        for(Customer customer : customers){
            System.out.println(customer.getCccd());
            defTabMod.addRow(new Object[] {
                customer.getMakh(), customer.getCccd(), customer.getHoten(), customer.getGioitinh(),
                customer.getNgaysinh(), customer.getSdt(), customer.getEmail(), customer.getDiachi()
            });
        }
        
    }
    
    /**
     * Phần HomePage
     */
    private void setHomePage(){
        pnlThue.setVisible(false);
        pnlTra.setVisible(false);
        pnlTheKH.setVisible(false);
        pnlHome.setVisible(true);
        tabHome.setBackground(Color.white);
        tabTra.setBackground(lightBlue);
        tabTheKH.setBackground(lightBlue);
        tabThue.setBackground(lightBlue);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDMK;
    private javax.swing.JButton btnHome_Inf_OK;
    private javax.swing.JButton btnHome_pass_OK;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOkTra;
    private javax.swing.JButton btnResetTra;
    private javax.swing.JButton btnRstTheKH;
    private javax.swing.JButton btnRstThue;
    private javax.swing.JButton btnTK;
    private javax.swing.JButton btnTTND;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnThue;
    private javax.swing.JButton btnThue_Huy;
    private javax.swing.JButton btnThue_Luu;
    private javax.swing.JButton btnTimKiemTheKH;
    private javax.swing.JButton btnTimKiemThue;
    private javax.swing.JButton btnTra;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JDialog dlgDmk;
    private javax.swing.JDialog dlgThue;
    private javax.swing.JDialog dlgTra;
    private javax.swing.JFrame frmPerInf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCD;
    private javax.swing.JLabel lblCD1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTheKH;
    private javax.swing.JLabel lblThue;
    private javax.swing.JLabel lblThue_MAKH;
    private javax.swing.JLabel lblThue_MaDia1;
    private javax.swing.JLabel lblThue_NgayTra1;
    private javax.swing.JLabel lblThue_SoLuong1;
    private javax.swing.JLabel lblTra;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLayoutSize;
    private javax.swing.JPanel pnlNavigationBar;
    private javax.swing.JPanel pnlTheKH;
    private javax.swing.JPanel pnlTheKHProcess;
    private javax.swing.JPanel pnlThue;
    private javax.swing.JPanel pnlThueProcess;
    private javax.swing.JPanel pnlThue_Them1;
    private javax.swing.JPanel pnlTra;
    private javax.swing.JPanel pnlTra_Them;
    private javax.swing.JSeparator sprtCD;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabTheKH;
    private javax.swing.JPanel tabThue;
    private javax.swing.JPanel tabTra;
    private javax.swing.JTable tblTheKH;
    private javax.swing.JTable tblThue;
    private javax.swing.JTable tblTra;
    private javax.swing.JLabel txtHome_CCCD;
    private javax.swing.JLabel txtHome_gt;
    private javax.swing.JLabel txtHome_ht;
    private javax.swing.JLabel txtHome_mnv;
    private javax.swing.JLabel txtHome_ns;
    private javax.swing.JPasswordField txtMkcu;
    private javax.swing.JPasswordField txtMkmoi;
    private javax.swing.JTextField txtTKTra;
    private javax.swing.JLabel txtThongBaoTheKH;
    private javax.swing.JLabel txtThongBaoThue;
    private javax.swing.JLabel txtThongBaoTra;
    private javax.swing.JTextField txtThue_MaDia;
    private javax.swing.JTextField txtThue_MaKH;
    private com.toedter.calendar.JDateChooser txtThue_NgayTra;
    private javax.swing.JTextField txtThue_SoLuong;
    private javax.swing.JTextField txtTimKiemTheKH;
    private javax.swing.JTextField txtTimKiemThue;
    private javax.swing.JTextField txtTra_ID;
    private javax.swing.JTextField txtTra_PhuPhi;
    // End of variables declaration//GEN-END:variables

}
