/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.main;

import java.awt.Color;

/**
 *
 * @author vduct
 */
public class UI_Manager extends javax.swing.JFrame {

    /**
     * Creates new form UI_Staff
     */
    public UI_Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLayoutSize = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        lblCD = new javax.swing.JLabel();
        sprtCD = new javax.swing.JSeparator();
        tabUpdate = new javax.swing.JPanel();
        lblThue = new javax.swing.JLabel();
        tabNV = new javax.swing.JPanel();
        lblTra = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlUpdate = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlProcess = new javax.swing.JPanel();
        lblThaotac = new javax.swing.JLabel();
        cbThaotac = new javax.swing.JComboBox<>();
        lblDia = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        lblGia = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lblLoai = new javax.swing.JLabel();
        txtLoai = new javax.swing.JTextField();
        lblSl = new javax.swing.JLabel();
        txtSl = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        pnlNV = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STAFF");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlLayoutSize.setBackground(new java.awt.Color(204, 204, 255));

        pnlMenu.setBackground(new java.awt.Color(102, 102, 255));
        pnlMenu.setPreferredSize(new java.awt.Dimension(270, 500));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCD.setFont(new java.awt.Font("Script MT Bold", 3, 48)); // NOI18N
        lblCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCD.setText("CD");
        pnlMenu.add(lblCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 60, 88, 82));

        sprtCD.setForeground(new java.awt.Color(0, 0, 0));
        pnlMenu.add(sprtCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 132, 88, 10));

        tabUpdate.setBackground(new java.awt.Color(204, 204, 255));
        tabUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabUpdateMouseClicked(evt);
            }
        });

        lblThue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblThue.setText("Cập nhật sản phẩm");

        javax.swing.GroupLayout tabUpdateLayout = new javax.swing.GroupLayout(tabUpdate);
        tabUpdate.setLayout(tabUpdateLayout);
        tabUpdateLayout.setHorizontalGroup(
            tabUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabUpdateLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblThue)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        tabUpdateLayout.setVerticalGroup(
            tabUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabUpdateLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblThue, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pnlMenu.add(tabUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        tabNV.setBackground(new java.awt.Color(204, 204, 255));
        tabNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabNVMouseClicked(evt);
            }
        });

        lblTra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTra.setText("Danh sách nhân viên");

        javax.swing.GroupLayout tabNVLayout = new javax.swing.GroupLayout(tabNV);
        tabNV.setLayout(tabNVLayout);
        tabNVLayout.setHorizontalGroup(
            tabNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNVLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTra, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabNVLayout.setVerticalGroup(
            tabNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabNVLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblTra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pnlMenu.add(tabNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 278, 270, -1));

        pnlContent.setBackground(new java.awt.Color(204, 204, 255));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlUpdate.setBackground(new java.awt.Color(255, 255, 255));
        pnlUpdate.setPreferredSize(new java.awt.Dimension(536, 350));
        pnlUpdate.setLayout(new javax.swing.BoxLayout(pnlUpdate, javax.swing.BoxLayout.Y_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlUpdate.add(jScrollPane1);

        pnlProcess.setBackground(new java.awt.Color(255, 255, 255));
        pnlProcess.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThaotac.setText("Thao tác:");
        pnlProcess.add(lblThaotac, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 73, -1));

        cbThaotac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thêm sản phẩm", "Sửa giá ", " " }));
        pnlProcess.add(cbThaotac, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 14, -1, -1));

        lblDia.setText("Tên đĩa:");
        pnlProcess.add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 17, 96, -1));
        pnlProcess.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 14, 130, -1));

        lblGia.setText("Giá thuê:");
        pnlProcess.add(lblGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, 73, -1));
        pnlProcess.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 48, 120, -1));

        lblMa.setText("Mã đĩa:");
        pnlProcess.add(lblMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 51, 96, -1));
        pnlProcess.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 48, 130, -1));

        lblLoai.setText("Loại:");
        pnlProcess.add(lblLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 73, -1));
        pnlProcess.add(txtLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 82, 120, -1));

        lblSl.setText("Số lượng:");
        pnlProcess.add(lblSl, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 85, 96, -1));

        txtSl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlActionPerformed(evt);
            }
        });
        pnlProcess.add(txtSl, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 82, 130, -1));

        btnLuu.setText("Lưu");
        pnlProcess.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 80, 40));

        pnlUpdate.add(pnlProcess);

        pnlContent.add(pnlUpdate, "card2");

        pnlNV.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlNVLayout = new javax.swing.GroupLayout(pnlNV);
        pnlNV.setLayout(pnlNVLayout);
        pnlNVLayout.setHorizontalGroup(
            pnlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        pnlNVLayout.setVerticalGroup(
            pnlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        pnlContent.add(pnlNV, "card3");

        javax.swing.GroupLayout pnlLayoutSizeLayout = new javax.swing.GroupLayout(pnlLayoutSize);
        pnlLayoutSize.setLayout(pnlLayoutSizeLayout);
        pnlLayoutSizeLayout.setHorizontalGroup(
            pnlLayoutSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayoutSizeLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLayoutSizeLayout.setVerticalGroup(
            pnlLayoutSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenu.getAccessibleContext().setAccessibleName("Menu");

        getContentPane().add(pnlLayoutSize, java.awt.BorderLayout.CENTER);
        pnlLayoutSize.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabUpdateMouseClicked
        pnlUpdate.setVisible(true);
        pnlNV.setVisible(false);
        tabUpdate.setBackground(Color.white);
        tabNV.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_tabUpdateMouseClicked

    private void tabNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabNVMouseClicked
        pnlNV.setVisible(true);
        pnlUpdate.setVisible(false);
        tabNV.setBackground(Color.white);
        tabUpdate.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_tabNVMouseClicked

    private void txtSlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbThaotac;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCD;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblSl;
    private javax.swing.JLabel lblThaotac;
    private javax.swing.JLabel lblThue;
    private javax.swing.JLabel lblTra;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlLayoutSize;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNV;
    private javax.swing.JPanel pnlProcess;
    private javax.swing.JPanel pnlUpdate;
    private javax.swing.JSeparator sprtCD;
    private javax.swing.JPanel tabNV;
    private javax.swing.JPanel tabUpdate;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtLoai;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSl;
    // End of variables declaration//GEN-END:variables
}
